// Code generated by jtd-codegen for TypeScript v0.2.1

export type WsResponse =
  | WsResponseInvokeAck
  | WsResponseInvokeReq
  | WsResponseOnEvent
  | WsResponseRegisterAck
  | WsResponseSubscribeAck;

export interface WsResponseInvokeAck {
  command: "invokeAck";
  conversation: number;
  message: string;
  success: boolean;
}

export interface WsResponseInvokeReq {
  command: "invokeReq";
  conversation: number;
  payload: string;
  requester: string;
}

export interface WsResponseOnEvent {
  command: "onEvent";
  conversation: number;
  data: string;
  event: string;
}

export interface WsResponseRegisterAck {
  command: "registerAck";
  conversation: number;
  message: string;
  success: boolean;
}

export interface WsResponseSubscribeAck {
  command: "subscribeAck";
  conversation: number;
  message: string;
  success: boolean;
}
