// Code generated by jtd-codegen for TypeScript v0.2.1

export type WsResponse =
  | WsResponseInvokeAck
  | WsResponseInvokeReq
  | WsResponseOnEvent
  | WsResponseRegisterAck
  | WsResponseServerError
  | WsResponseSubscribeAck;

export interface WsResponseInvokeAck {
  command: "invokeAck";
  message: string;
  success: boolean;
}

export interface WsResponseInvokeReq {
  command: "invokeReq";
  payload: string;
  requester: string;
}

export interface WsResponseOnEvent {
  command: "onEvent";
  data: string;
  event: string;
}

export interface WsResponseRegisterAck {
  command: "registerAck";
  message: string;
  success: boolean;
}

export interface WsResponseServerError {
  command: "serverError";
  message: string;
  success: boolean;
}

export interface WsResponseSubscribeAck {
  command: "subscribeAck";
  message: string;
  success: boolean;
}
