// Code generated by jtd-codegen for TypeScript v0.2.1

export type WsRequest =
  | WsRequestInvoke
  | WsRequestRegister
  | WsRequestSubscribe;

export interface WsRequestInvoke {
  command: "invoke";
  id: string;
  payload: string;
}

export interface WsRequestRegister {
  command: "register";
  id: string;
  name: string;
  events?: string[];
}

export interface WsRequestSubscribe {
  command: "subscribe";
  event: string;
  id: string;
}
