#!/bin/bash

export PATH="$PATH:../utils/yaml2json"

echo "// Code generated by spec/compile.sh; DO NOT EDIT." >../api/index.ts

convert() {
  mkdir -p ../api/$2
  yaml2json $1 | jtd-codegen - --log-format=minimal --root-name=$2 --typescript-out=../api/$2

  echo "export * from './$2/index.ts';" >>../api/index.ts
}

convert wsrequest.yaml wsRequest
convert wsresponse.yaml wsResponse

deno fmt -q ../api/
